export enum Types {
  FETCH_SPOONACULAR_RECIPES = 'FETCH_SPOONACULAR_RECIPES',
  FETCH_SPOONACULAR_RECIPE_BY_ID = 'FETCH_SPOONACULAR_RECIPE_BY_ID',
  FETCH_FAVORITES = 'FETCH_FAVORITES',
  SET_FAVORITES = 'SET_FAVORITES'
}
