export enum Types {
  SET_ERROR = 'SET_ERROR',
  FETCH_SPOONACULAR_RECIPES = 'FETCH_SPOONACULAR_RECIPES',
  FETCH_SPOONACULAR_RECIPE_BY_ID = 'FETCH_SPOONACULAR_RECIPE_BY_ID',
  SELECT_SPOONACULAR_RECIPE = 'SELECT_SPOONACULAR_RECIPE',
  FETCH_FAVORITES = 'FETCH_FAVORITES',
  SET_FAVORITES = 'SET_FAVORITES',
  SET_QUERY_INGREDIENTS = 'SET_QUERY_INGREDIENTS',
  SET_QUERY_NUTRIENTS = 'SET_QUERY_NUTRIENTS'
}
